apiVersion: v1
kind: Pod
metadata:
  labels:
    name: jenkins-slave
  spec:
    containers:
      - name: docker
        image: docker
        volumeMounts:
          - name: docker-sock-volume
            mountPath: /var/run/docker.sock
        command:
          - cat
        tty: true
        volumes:
          - name: docker-sock-volume
            hostPath:
            path: /var/run/docker.sock